##################################################
#               CREATE HOUSEWORK                 #
##################################################
POST http://localhost:5000/houseWork/ HTTP/1.1
Content-Type: application/json

{
  "title": "Wash the dishes",
  "description": "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
  "reward": 250,
  "ownerId": "$ilven1eaf"
}



##################################################
#               UPDATE HOUSEWORK                 #
##################################################
PUT http://localhost:5000/houseWork/ HTTP/1.1
Content-Type: application/json

{ "houseWorkId": "5f7ecd13a8e6d92f1c1d9dd3",
  "title": "Wash the Cloths",
  "description": "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
  "reward": 250,
  "ownerId": "$ilven1eaf"
}







##################################################
#               DELETE HOUSEWORK                 #
##################################################
DELETE http://localhost:5000/houseWork/ HTTP/1.1
Content-Type: application/json

{ 
  "houseWorkId": "5f7ece906bf3a51c4075bfbc"  
}





##################################################
#               GEL ALL HOUSEWORKS                 #
##################################################
GET http://localhost:5000/houseWork/all HTTP/1.1
